#!/usr/bin/env python3
"""Generate active governance/specification documentation from canonical contracts."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = ROOT / "contracts"
DOCS = ROOT / "docs"
COMPONENT_DOCS = DOCS / "components"
GENERATED = DOCS / "generated"
AGENT_PROTOCOL = ROOT / "governance" / "agent-protocol"
AGENT_PROTOCOL_INSTANCE = AGENT_PROTOCOL / "ai-governance-protocol.v1.1.json"
AGENT_PROFILE = AGENT_PROTOCOL / "profiles" / "gel-tutorial-writer.profile.json"

SOURCE_FILES = [
    "documentation_governance.json",
    "component_boundaries.json",
    "state_ownership.json",
    "release_gate.json",
    "release_identity.json",
    "verification_semantics.json",
    "dependency_lock_policy.json",
]


def load(name: str) -> dict[str, Any]:
    return json.loads((CONTRACTS / name).read_text(encoding="utf-8"))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def bullets(items: list[str]) -> list[str]:
    return [f"- {item}" for item in items] if items else ["- None."]


def render_component(component: dict[str, Any]) -> str:
    lines = [
        f"# {component['name']} — active component spec",
        "",
        "> Generated from `contracts/component_boundaries.json`. Do not edit this file directly.",
        "",
        f"**Component ID:** `{component['id']}`  ",
        f"**Status:** `{component['status']}`",
        "",
    ]
    sections = [
        ("Role", [component["role"]]),
        ("Scope", component["scope"]),
        ("Authority", component["authority"]),
        ("Reads", [f"`{x}`" for x in component["reads"]]),
        ("Writes", [f"`{x}`" for x in component["writes"]]),
        ("Must not write", [f"`{x}`" for x in component["must_not_write"]]),
        ("State transitions", component["state_transitions"]),
        ("Failure semantics", component["failure_semantics"]),
        ("Dependencies", component["dependencies"]),
        ("Tests", [f"`{x}`" if "/" in x or x.startswith("tools/") else x for x in component["tests"]]),
    ]
    for title, values in sections:
        lines.extend([f"## {title}", "", *bullets(values), ""])
    return "\n".join(lines).rstrip() + "\n"


def render_governance(docgov: dict[str, Any]) -> str:
    lines = [
        "# Project governance",
        "",
        "> Generated from `contracts/documentation_governance.json`. The JSON contract is authoritative.",
        "",
        "## Documentation authority order",
        "",
    ]
    for item in sorted(docgov["authority_order"], key=lambda x: x["rank"]):
        lines.extend([
            f"{item['rank']}. **{item['label']}** — {item['rule']}",
        ])
    lines.extend([
        "",
        "## Active component specification contract",
        "",
        "Every active component spec must contain all of these sections:",
        "",
        *[f"- {x}" for x in docgov["active_spec_required_sections"]],
        "",
        "## Same-change rule",
        "",
        docgov["same_change_rule"],
        "",
        "## ADR policy",
        "",
        docgov["adr_rule"],
        "",
        "Allowed ADR statuses: " + ", ".join(f"`{x}`" for x in docgov["adr_statuses"]) + ".",
        "",
        "## Generated-index rule",
        "",
        docgov["index_rule"],
        "",
        "## State classification",
        "",
        *[f"- **{name}** — {rule}" for name, rule in docgov.get("state_classification_taxonomy", {}).items()],
        "",
        "## AI-agent meta-governance",
        "",
        docgov.get("meta_governance_protocol_rule", "No project-specific meta-governance protocol is active."),
        "",
    ])
    return "\n".join(lines)


def render_architecture(components: dict[str, Any], ownership: dict[str, Any]) -> str:
    active = components["components"]
    lines = [
        "# Architecture and component boundaries",
        "",
        "> Generated from `contracts/component_boundaries.json` and `contracts/state_ownership.json`.",
        "",
        "## Current architecture",
        "",
        "```text",
        "GEL server (authoritative live source)",
        "  ├─ tutorial-list / summary / edit / print source representations",
        "  │",
        "  ├─> Rust GEL session (N1/N2b; login POST only) ──> ephemeral JSON/HTML snapshots",
        "  │",
        "  ├─> N2-PW1 Playwright evidence harness ──> gitignored privacy-safe evidence",
        "  │      └─ manual login only; tutorial POST serialization observed then ABORTED",
        "  │      ├─ New-form GET /add/{uid}/0/{type} ──> N2b NewTutorialForm parser",
        "  │      │                                      └─> validated New source authority",
        "  │                                             └─> Rust pure parsers",
        "  │                                                  └─> reconciliation / semantic revision state",
        "  │                                                       └─> offline POST mapper (NO NETWORK WRITE)",
        "  │",
        "  ├─> RustArchiver A2 ──> canonical schema-v2 SQLite archive",
        "  │      └─> crate-private ArchiveSyncRepository ──> transactional materialization/reconciliation",
        "  │",
        "  ├─> Python v4.9 archiver oracle ──> historical/reference parity evidence only",
        "  │",
        "  └─> D1 archive-schema migrator ──> separate noncanonical v2 candidate DB",
        "",
        "Canonical JSON contracts ──> generated Rust GEL compatibility projection",
        "                         └─> generated governance/specification documentation",
        "Private fixture capture ──> Git-ignored evidence ──> Rust comparator/release evidence",
        "",
        "Dependency manifests ──> governed lock tooling ──> Cargo.lock + package-lock.json",
        "                                             └─> dependency-lock manifest",
        "Contracts/plan/locks ──> current-state projection (NON-AUTHORITATIVE)",
        "Exact source+locks+toolchain ──> strict GRI evidence ──> no-rebuild package ──> verified archive receipt",
        "Portable CI ──> evidence only; never strict acceptance",
        "AI Governance Protocol v1.1 + GEL profile ──> agent workflow/evidence/promotion only (NON-RUNTIME AUTHORITY)",
        "```",
        "",
        "## Active components",
        "",
        "| Component | Status | Role |",
        "| --- | --- | --- |",
    ]
    for c in active:
        lines.append(f"| `{c['id']}` | `{c['status']}` | {c['role']} |")
    lines.extend([
        "",
        "## Planned but not active",
        "",
        *[f"- `{x}`" for x in components.get("planned_not_active", [])],
        "",
        "Planned components have no current write authority. Their ownership must be added to the canonical contracts in the same change that activates them.",
        "",
        "## Boundary rules",
        "",
        "- Opaque GEL form IDs belong to the canonical field contract/generated compatibility layer, not SQL/domain/UI code.",
        "- Parsers and reconciliation are pure derived-state components; they do not write GEL or canonical SQLite.",
        "- The semantic model produces editable derived state; it does not mutate archive history.",
        "- The POST mapper produces an ephemeral payload only and has no transport/network authority.",
        "- The Rust GEL session owns cookies and authenticated read transport only: exactly two login-handshake POSTs are allowed, while all exposed acquisition operations are fixed GETs; it exposes no generic request or tutorial mutation API.",
        "- N2b extends that fixed GET surface only with `/study/tutorials/add/{student_uid}/0/{ttype_raw}` and validates the returned New form separately from historical Revision edit forms.",
        "- The N2b New-form parser is the sole production writer of validated New-form source state and opaque hidden-teacher authority; it forbids `datetime`, retains no raw HTML, and owns no POST/network capability.",
        "- Credentials are transient inputs to the Rust GEL session and are not retained as project state; student email-like API fields are stripped before roster/profile JSON leaves the session boundary.",
        "- N2-PW1 is evidence-only tooling: its browser firewall is installed before login, it never reads login bodies/password values, and every tutorial mutation attempt is aborted. It may record client-side changed-teacher serialization but cannot establish server reassignment authority.",
        "- N2-PW1 treats latest tutorial as the established New prepopulation source and persists only field relationships/classifications, never raw tutorial values.",
        "- A2 makes RustArchiver the production canonical local archive orchestrator and the crate-private ArchiveSyncRepository the sole SQLite write capability; Python v4.9 remains historical/reference parity authority only.",
        "- D1 schema v2 is executable repository authority for the target archive shape, but its migration tool writes only separate noncanonical candidate databases; it does not cut over runtime ownership.",
        "- Schema v2 separates API identities, candidate source states and governed associations; blocked authority statuses carry no source-state reference.",
        "- The Viewer and future UI are not permitted to bypass the repository/source ownership contracts.",
        "- Dependency lock state is a reviewed decision with one writer; release/build commands use the root Cargo workspace lock and `npm ci`.",
        "- `governance/current-state.json` is generated projection state only. It summarizes higher-authority inputs and cannot override them.",
        "- Strict release acceptance is immutable external evidence bound to the exact source fingerprint, dependency locks and toolchain identity; CI cannot self-promote it.",
        "- Packaging occurs only after strict acceptance, revalidates the source fingerprint, performs no rebuild, and verifies the exact final archive bytes.",
        "- The generic AI Governance Protocol and GEL project profile are reviewed meta-governance decisions. They bind agent workflow/claims to existing contracts and may not override GEL runtime/domain semantics.",
        "",
        "## Source/decision/derived/projection/evidence rule",
        "",
        "A parser/model output, projection or evidence artifact is never promoted to source/decision authority merely because it is convenient to consume. Five-way state kind, writers, retention and invalidation are enumerated in `contracts/state_ownership.json`.",
        "",
    ])
    return "\n".join(lines)


def render_state_ownership(ownership: dict[str, Any]) -> str:
    lines = [
        "# State ownership, writers and invalidation",
        "",
        "> Generated from `contracts/state_ownership.json`. The JSON contract is authoritative.",
        "",
        "## Global ownership rule",
        "",
        ownership["canonical_writer_rule"],
        "",
        "## Archive source-disappearance policy",
        "",
        ownership["archive_source_disappearance_policy"],
        "",
        "## State matrix",
        "",
        "| State | Class | State kind | Legacy source/derived | Canonical | Permitted writer(s) | Current materialization |",
        "| --- | --- | --- | --- | ---: | --- | --- |",
    ]
    for s in ownership["state_classes"]:
        writers = ", ".join(f"`{x}`" for x in s["permitted_writers"])
        lines.append(
            f"| `{s['id']}` | `{s['class']}` | `{s['state_kind']}` | `{s['source_or_derived']}` | {'yes' if s['canonical'] else 'no'} | {writers} | {s['current_materialization']} |"
        )
    lines.extend(["", "## Retention and invalidation", ""])
    for s in ownership["state_classes"]:
        lines.extend([
            f"### `{s['id']}`",
            "",
            f"**Retention:** {s['retention']}",
            "",
            f"**Invalidation:** {s['invalidation']}",
            "",
        ])
    return "\n".join(lines)


def render_release_gate(gate: dict[str, Any]) -> str:
    lines = [
        "# Release gate",
        "",
        "> Generated from `contracts/release_gate.json`. The JSON contract and executable gate are authoritative over this prose.",
        "",
        "## Profiles",
        "",
    ]
    for name, profile in gate["profiles"].items():
        lines.extend([
            f"### `{name}`",
            "",
            profile["description"],
            "",
            f"Missing private fixture policy: **{profile['missing_private_fixture_policy'].upper()}**.",
            f"Missing dependency lock when corresponding generator is unavailable: **{profile.get('missing_dependency_lock_tool_policy', 'unspecified').upper()}**.",
            "",
        ])
    lines.extend([
        f"Current release scope: **`{gate.get('current_release_scope', 'unspecified')}`**.",
        "",
        "## Check result taxonomy",
        "",
        "| Result | Meaning |",
        "| --- | --- |",
    ])
    for status, meaning in gate["result_taxonomy"].items():
        lines.append(f"| **{status}** | {meaning} |")
    lines.extend([
        "",
        "## Acceptance status taxonomy",
        "",
        "| Status | Meaning |",
        "| --- | --- |",
    ])
    for status, meaning in gate.get("acceptance_status_taxonomy", {}).items():
        lines.append(f"| **{status}** | {meaning} |")
    lines.extend([
        "",
        "## Current checks",
        "",
        "| Check | Evidence class | Portable | Strict | Purpose |",
        "| --- | --- | ---: | ---: | --- |",
    ])
    for c in gate["checks"]:
        profiles = set(c["profiles"])
        lines.append(
            f"| `{c['id']}` | `{c.get('evidence_class', 'structural')}` | {'required' if 'portable' in profiles else '—'} | {'required' if 'strict' in profiles else '—'} | {c['purpose']} |"
        )
    lines.extend([
        "",
        "## D1 archive-schema invariant",
        "",
        "`archive_schema_v2` runs in both portable and strict profiles. It validates fresh schema creation, legacy-v1 migration, foreign-key enforcement, relational class membership, collision-safe identity/state associations, source-presence lifecycle, privacy minimization, and the prohibition on `INSERT OR REPLACE`.",
        "",
        "## D2 Rust repository invariant",
        "",
        "`archive_repository` runs in both portable and strict profiles under `python -S`. It enforces the public read-only/query-only repository boundary, the crate-private candidate-only sync writer, exact D1 source-state fingerprint parity, transactional rollback/invalidation semantics, immutable canonical tutorial IDs, and the prohibition on D2 production-writer cutover.",
        "",
        "## N1 Rust GEL session invariant",
        "",
        "`gel_session` runs in both portable and strict profiles under `python -S`. It validates the fixed endpoint-specific read surface, exactly two login-handshake POST call sites, private cookie/credential ownership, fail-closed authentication semantics, student-email minimization, no generic transport API and no tutorial mutation authority. Credentialed live parity remains a separate manual probe and is never executed by the release gate.",
        "",
        "## N2-PW1 zero-write browser invariant",
        "",
        "`n2_playwright_zero_write` runs in both portable and strict profiles under `python -S` and remains offline. It statically/behaviourally validates the zero-write browser evidence boundary. Changed-teacher submit serialization is a deferred, non-blocking residual and is not an N2 functional gate.",
        "",
        "## N2a semantic/POST authority invariant",
        "",
        "`n2a_semantic_post` runs in both portable and strict profiles under `python -S`. It validates canonical GEL field identity, distinct New/Revision origins and submission types, complete New `datetime` omission, exact Revision source timestamp, immutable New/Revision teacher authority, first-ever New support, absence of fabricated New identity, and the offline-only POST mapper boundary.",
        "",
        "## Named scopes",
        "",
    ])
    for scope_id, scope in gate.get("scopes", {}).items():
        lines.extend([
            f"### `{scope_id}`",
            "",
            scope["purpose"],
            "",
            "Checks: " + ", ".join(f"`{check}`" for check in scope["checks"]) + ".",
            "",
        ])
    parity = gate["private_fixture_parity"]
    lines.extend([
        "",
        "## Private fixture parity invariant",
        "",
        f"Strict baseline: **{parity['required_fixture_count']} fixtures / {parity['required_field_count']} fields / {parity['required_ok']} OK / {parity['required_mismatch']} known mismatches / {parity['required_unavailable']} unavailable**.",
        "",
        parity["rule"],
        "",
        f"Default private fixture root: `{parity['default_fixture_root']}/`. Set `{parity['fixture_root_env']}` to validate a private fixture tree stored outside the repository checkout.",
        "",
        "Allowed mismatch set:",
        "",
    ])
    for m in parity["allowed_mismatches"]:
        lines.append(f"- `{m['count']}× {m['field']}` with archive `{m['archive_value']}` and edit `{m['edit_value']}`.")
    collision = gate["private_collision_authority"]
    lines.extend([
        "",
        "## Private C3 collision-authority invariant",
        "",
        f"Strict collision fixtures: **{collision['required_fixture_count']}** (`"
        + "`, `".join(collision["required_labels"])
        + "`).",
        "",
        "The identical-state fixture must preserve every API tutorial ID while keeping candidate source entries group-owned; revision resolves only through shared-identical authority. The divergent-state fixture must keep all source states group-owned and block revision-by-ID.",
        "",
        f"The same `{collision['fixture_root_env']}` root override supplies these reconciliation fixtures from `{collision['expected_subdir']}` and `{collision['raw_subdir']}`.",
        "",
    ])
    round_trip = gate["private_post_round_trip"]
    lines.extend([
        "## Private C4 offline POST round-trip invariant",
        "",
        f"Strict C4 fixtures: **{round_trip['required_fixture_count']}** edit/archive pairs, including **{round_trip['required_final_fixture_count']}** Final fixtures and **{round_trip['required_absent_source_discrepancy_count']}** governed historical absent discrepancies.",
        "",
        "Each fixture is parsed and validated, reconstructed as a Revision semantic state, serialized by the Rust POST mapper, and compared to an independently reconstructed expected successful-control map. Exact key/value equality is required; Final Reading must be present and archive absent remains authoritative.",
        "",
        f"The same `{round_trip['fixture_root_env']}` root override supplies these fixtures from `{round_trip['expected_subdir']}` and `{round_trip['raw_subdir']}`.",
        "",
        "## Live-write prohibition",
        "",
        gate["live_write_rule"],
        "",
        "## Gate growth",
        "",
        gate["future_growth_rule"],
        "",
        "## Commands",
        "",
        "```fish",
        "# Portable CI/development evidence only",
        "python tools/release_gate.py --profile portable --scope ui1d",
        "",
        "# Target-host strict acceptance; evidence path must be outside source",
        "python tools/release_gate.py --profile strict --scope ui1d --evidence-out /evidence/gel/<run-id>/strict-result.json",
        "",
        "# Package exact accepted source without rebuilding",
        "python tools/package_release.py --evidence /evidence/gel/<run-id>/strict-result.json --output /artifacts/gel-rust-bootstrap.zip",
        "python tools/verify_release_archive.py /artifacts/gel-rust-bootstrap.zip",
        "```",
        "",
    ])
    return "\n".join(lines)


def render_adr_readme(docgov: dict[str, Any]) -> str:
    return "\n".join([
        "# Architecture Decision Records — historical only",
        "",
        docgov["adr_rule"],
        "",
        "Every ADR file named `ADR-*.md` must declare one of these statuses near the top:",
        "",
        *[f"- `{x}`" for x in docgov["adr_statuses"]],
        "",
        "An accepted historical ADR records why a decision was made. If current executable contracts/specs later change, the ADR is not edited into runtime authority; mark it `superseded` where appropriate and update the active authority instead.",
        "",
    ])


def render_adr_template(docgov: dict[str, Any]) -> str:
    return "\n".join([
        "# ADR-NNN — Decision title",
        "",
        "**Status:** proposed",
        "",
        "**Date:** YYYY-MM-DD",
        "",
        "## Context",
        "",
        "Historical context for the decision.",
        "",
        "## Decision",
        "",
        "Decision made at the time.",
        "",
        "## Consequences",
        "",
        "Consequences known at the time.",
        "",
        "## Current-authority note",
        "",
        docgov["adr_rule"],
        "",
    ])


def render_agent_governance_profile() -> str:
    protocol = json.loads(AGENT_PROTOCOL_INSTANCE.read_text(encoding="utf-8"))
    profile = json.loads(AGENT_PROFILE.read_text(encoding="utf-8"))
    authority = profile["authorityBinding"]
    lines = [
        "# AI-agent governance profile",
        "",
        "> Generated from `governance/agent-protocol/ai-governance-protocol.v1.1.json` and the GEL project profile. This page is a projection and not runtime authority.",
        "",
        f"- Protocol: `{protocol['protocolId']} v{protocol['protocolVersion']}`",
        f"- Profile: `{profile['profileId']} v{profile['profileVersion']}`",
        f"- Role: `{authority['protocolRole']}`",
        f"- Runtime authority: `{str(authority['runtimeAuthority']).lower()}`",
        f"- Current-state semantics: `{authority['currentStateSemantics']}`",
        "",
        "## Runtime authority binding",
        "",
        "The generic protocol does not define GEL field IDs, tutorial semantics, archive ownership, network endpoints, POST payloads, or UI edit authority. Those remain in the existing canonical GEL contracts/tests.",
        "",
        "Bound contracts:",
        "",
    ]
    lines += [f"- `{key}` → `{path}`" for key, path in profile["contractBindings"].items()]
    lines += [
        "",
        "## Gate profiles",
        "",
        "| Profile | Missing required private evidence | SKIP counts as PASS | Promotion ceiling |",
        "| --- | --- | ---: | --- |",
    ]
    for name, gate in profile["gateProfiles"].items():
        lines.append(f"| `{name}` | `{gate['missingRequiredPrivateEvidence']}` | {'yes' if gate['skipMayCountAsPass'] else 'no'} | `{gate['promotionCeiling']}` |")
    lines += [
        "",
        "## Dependency-lock generator exception",
        "",
        f"- Exception: `{profile['promotionPolicy']['missingDependencyIdentity']['toolUnavailableException']['portableResult']}` in portable only when auto-detected; strict result `{profile['promotionPolicy']['missingDependencyIdentity']['toolUnavailableException']['strictResult']}`.",
        f"- Manual override allowed: `{str(profile['promotionPolicy']['missingDependencyIdentity']['toolUnavailableException']['manualOverrideAllowed']).lower()}`.",
        f"- Promotion ceiling while active: `{profile['promotionPolicy']['missingDependencyIdentity']['toolUnavailableException']['promotionCeiling']}`.",
        "- Network failure or package-manager command failure is not equivalent to an unavailable generator executable.",
        "",
        "## Side-effect policy",
        "",
        f"- Automated tutorial writes: `{str(profile['gateSideEffectPolicy']['automatedTutorialWrites']).lower()}`",
        f"- Automated canonical archive writes: `{str(profile['gateSideEffectPolicy']['automatedArchiveCanonicalWrites']).lower()}`",
        "",
        "## Validation",
        "",
        "`check:governance` invokes `tools/check_ai_governance_protocol.py`, which validates protocol/profile consistency, references to existing GEL gates/components/state, lifecycle claim semantics, and the non-runtime-authority boundary.",
        "",
    ]
    return "\n".join(lines)


def documentation_entries(components: dict[str, Any]) -> list[tuple[int, str, str, str]]:
    entries: list[tuple[int, str, str, str]] = [
        (1, "contracts/*.json", "canonical", "Executable contracts"),
        (1, "Cargo.lock + writer-ui/package-lock.json", "decision", "Governed dependency-resolution identity"),
        (1, "contracts/dependency_lock_policy.json", "canonical", "Portable lock-generator exception and strict dependency-identity rules"),
        (1, "governance/current-state.schema.json", "canonical", "Executable current-state projection schema"),
        (1, "gel-core/tests/*.rs", "canonical", "Executable behavioural tests"),
        (2, "docs/components/*.md", "generated", "Active component specifications"),
        (3, "docs/GOVERNANCE.md", "generated", "Documentation governance"),
        (3, "docs/ARCHITECTURE.md", "generated", "Architecture and boundaries"),
        (3, "docs/STATE_OWNERSHIP.md", "generated", "State ownership and invalidation"),
        (3, "docs/SEMANTIC_FORM_MODEL.md", "handwritten", "Cross-component semantic model notes"),
        (3, "docs/DEVELOPMENT_PLAN.md", "generated", "Cross-component development plan"),
        (3, "governance/current-state.json", "generated projection", "Current project status; non-authoritative projection"),
        (3, "docs/generated/CURRENT_STATE.md", "generated projection", "Human current-state projection"),
        (3, "governance/dependency-lock-manifest.json", "generated", "Dependency lock identity/status"),
        (4, "docs/RELEASE_GATE.md", "generated", "Release operation and result taxonomy"),
        (4, "README.md", "handwritten", "Project operational entry point"),
        (5, "docs/adrs/*.md", "historical", "Historical decisions/templates"),
        (5, "docs/history/**", "historical", "Superseded plans/status material"),
    ]
    return entries


def render_doc_index(components: dict[str, Any]) -> str:
    lines = [
        "# Documentation index (generated)",
        "",
        "> Generated by `tools/generate_governance_artifacts.py`. Do not edit directly.",
        "",
        "## Authority index",
        "",
        "| Rank | Path | Mode | Purpose |",
        "| ---: | --- | --- | --- |",
    ]
    for rank, path, mode, purpose in documentation_entries(components):
        lines.append(f"| {rank} | `{path}` | `{mode}` | {purpose} |")
    lines.extend([
        "",
        "## Active component specs",
        "",
    ])
    for c in components["components"]:
        lines.append(f"- [`{c['id']}`](../components/{c['id']}.md) — {c['name']} (`{c['status']}`)")
    lines.extend([
        "",
        "## AI-agent meta-governance (not runtime authority)",
        "",
        f"- `governance/agent-protocol/ai-governance-protocol.v1.1.json` — `{sha256(AGENT_PROTOCOL_INSTANCE)}`",
        f"- `governance/agent-protocol/profiles/gel-tutorial-writer.profile.json` — `{sha256(AGENT_PROFILE)}`",
        "- `docs/generated/AI_GOVERNANCE_PROFILE.md` — generated human projection.",
        "",
        "These files govern agent workflow/evidence/promotion only and do not override GEL runtime/domain contracts.",
        "",
        "## Canonical governance-contract hashes",
        "",
        "| Contract | SHA-256 |",
        "| --- | --- |",
    ])
    for name in SOURCE_FILES:
        lines.append(f"| `{name}` | `{sha256(CONTRACTS / name)}` |")
    lines.extend([
        "",
        "The separate `CONTRACT_INDEX.md` indexes the G0 GEL field/evidence contracts.",
        "",
    ])
    return "\n".join(lines)


def outputs(docgov: dict[str, Any], components: dict[str, Any], ownership: dict[str, Any], gate: dict[str, Any]) -> dict[Path, str]:
    out: dict[Path, str] = {
        DOCS / "GOVERNANCE.md": render_governance(docgov),
        DOCS / "ARCHITECTURE.md": render_architecture(components, ownership),
        DOCS / "STATE_OWNERSHIP.md": render_state_ownership(ownership),
        DOCS / "RELEASE_GATE.md": render_release_gate(gate),
        DOCS / "adrs" / "README.md": render_adr_readme(docgov),
        DOCS / "adrs" / "ADR_TEMPLATE.md": render_adr_template(docgov),
        GENERATED / "DOCUMENTATION_INDEX.md": render_doc_index(components),
        GENERATED / "AI_GOVERNANCE_PROFILE.md": render_agent_governance_profile(),
    }
    for component in components["components"]:
        out[COMPONENT_DOCS / f"{component['id']}.md"] = render_component(component)
    return out


def write_or_check(path: Path, content: str, check: bool) -> bool:
    content = content.rstrip() + "\n"
    if check:
        if not path.exists():
            print(f"STALE: missing generated governance artifact {path.relative_to(ROOT)}")
            return False
        if path.read_text(encoding="utf-8") != content:
            print(f"STALE: {path.relative_to(ROOT)} differs from canonical governance contracts")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    docgov = load("documentation_governance.json")
    components = load("component_boundaries.json")
    ownership = load("state_ownership.json")
    gate = load("release_gate.json")

    ok = True
    for path, content in outputs(docgov, components, ownership, gate).items():
        ok &= write_or_check(path, content, args.check)
    if args.check and ok:
        print("generated governance artifacts: CURRENT")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
